// Tiny local subset of the existing utility classes. No runtime CDN.
const styles = {
  "absolute": "position:absolute",
  "fixed": "position:fixed",
  "hidden": "display:none!important",
  "flex": "display:flex",
  "flex-col": "flex-direction:column",
  "items-center": "align-items:center",
  "justify-center": "justify-content:center",
  "justify-between": "justify-content:space-between",
  "inset-0": "inset:0",
  "inset-x-0": "left:0;right:0",
  "top-0": "top:0",
  "bottom-6": "bottom:1.5rem",
  "bottom-24": "bottom:6rem",
  "right-3": "right:.75rem",
  "right-20": "right:5rem",
  "left-3": "left:.75rem",
  "z-10": "z-index:10",
  "z-[55]": "z-index:55",
  "z-[60]": "z-index:60",
  "pointer-events-none": "pointer-events:none",
  "h-screen": "height:100vh",
  "h-12": "height:3rem",
  "w-12": "width:3rem",
  "max-w-5xl": "max-width:64rem",
  "mx-auto": "margin-left:auto;margin-right:auto",
  "overflow-y-auto": "overflow-y:auto",
  "select-none": "user-select:none",
  "rounded-full": "border-radius:9999px",
  "gap-1": "gap:.25rem",
  "gap-2": "gap:.5rem",
  "gap-3": "gap:.75rem",
  "p-1": "padding:.25rem",
  "px-4": "padding-left:1rem;padding-right:1rem",
  "py-1.5": "padding-top:.375rem;padding-bottom:.375rem",
  "py-2": "padding-top:.5rem;padding-bottom:.5rem",
  "py-10": "padding-top:2.5rem;padding-bottom:2.5rem",
  "pt-3": "padding-top:.75rem",
  "pt-20": "padding-top:5rem",
  "pb-2": "padding-bottom:.5rem",
  "pb-8": "padding-bottom:2rem",
  "mt-1": "margin-top:.25rem",
  "mt-3": "margin-top:.75rem",
  "mb-1": "margin-bottom:.25rem",
  "mb-4": "margin-bottom:1rem",
  "col-span-full": "grid-column:1 / -1",
  "font-black": "font-weight:900",
  "font-bold": "font-weight:700",
  "font-semibold": "font-weight:600",
  "font-mono": "font-family:ui-monospace,monospace",
  "text-2xl": "font-size:1.5rem;line-height:2rem",
  "text-xl": "font-size:1.25rem;line-height:1.75rem",
  "text-base": "font-size:1rem;line-height:1.5rem",
  "text-sm": "font-size:.875rem;line-height:1.25rem",
  "text-xs": "font-size:.75rem;line-height:1rem",
  "text-[10px]": "font-size:10px",
  "text-red-500": "color:#ef4444",
  "text-white/40": "color:rgba(255,255,255,.4)",
  "text-white/50": "color:rgba(255,255,255,.5)",
  "text-white/60": "color:rgba(255,255,255,.6)",
  "text-white/70": "color:rgba(255,255,255,.7)",
  "bg-black/40": "background-color:rgba(0,0,0,.4)",
  "bg-white/10": "background-color:rgba(255,255,255,.1)",
  "bg-gradient-to-b": "background-image:linear-gradient(to bottom,rgba(0,0,0,.8),transparent)",
  "backdrop-blur": "backdrop-filter:blur(6px)",
  "tracking-tight": "letter-spacing:-.025em",
  "tracking-wider": "letter-spacing:.05em",
  "uppercase": "text-transform:uppercase",
  "leading-tight": "line-height:1.25",
  "line-clamp-2": "display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden"
};
export const UTILITY_CSS = Object.entries(styles)
  .map(([name, declarations]) => '[class~="' + name + '"]{' + declarations + '}')
  .join('') + '\n[class~="active:bg-white/30"]:active{background-color:rgba(255,255,255,.3)}';
